### ISSUE TITLE
App.js as index.js

### ISSUE THREAD

**Issue by AlexKVal** [BoomTownROI/boomstrap-react#14]
Isn't they suppose to be named as `index.js` ?

These
`src/Components/App.js`
`src/Mixins/App.js`
`src/Constants/App.js`
`src/App.js`
files do exactly what `index.js` files usually do.

**Comment by mfunkie** [comment]
I'm not terribly concerned with the nomenclature here as App.js is something that leaked out of our code base. I'm not opposed either as its transparent to the end user.

I did notice, however, that some of our components are missing from Components/App.js

@mcraiganthony since you added these, can you tackle adding them to App.js in src/Components and cut a new release?

**Comment by mfunkie** [comment]
I haven't forgotten about this, more just giving it some thought. I'll tackle updating our App.js files to be index,js this weekend some time.

**Comment by mfunkie** [comment]
Resolved by https://github.com/BoomTownROI/boomstrap-react/pull/22
